insert into public.equipment_reviews (
  id,
  title,
  slug,
  category,
  brand,
  model,
  cover_image_url,
  gallery,
  content_md,
  author_name,
  is_published,
  published_at,
  is_deleted
) values
(
  '11111111-1111-4111-8111-111111111111',
  'Yonex Percept 100D：穩定控球型球拍實測',
  'yonex-percept-100d-control-review',
  '球拍',
  'Yonex',
  'Percept 100D',
  '/images/seeds/reviews/racket-control.svg',
  '[]'::jsonb,
  '<p>Percept 100D 的甜區比傳統 97 平方吋控制拍更友善，適合想要穩定落點、又不想犧牲太多容錯的中高階球友。</p><h2>實打感受</h2><p>底線抽球有清楚的持球感，反拍切削很穩，網前處理也乾淨。缺點是主動加速時需要完整揮拍，力量不足的球友可能會覺得球速不夠免費。</p><ul><li>控球：9/10</li><li>旋轉：7.5/10</li><li>容錯：8/10</li></ul>',
  'JoJo Tennis 編輯部',
  true,
  '2026-06-01T00:00:00Z',
  false
),
(
  '22222222-2222-4222-8222-222222222222',
  'Poly Tour Rev：重旋轉球線適合誰？',
  'poly-tour-rev-spin-string-review',
  '球線',
  'Yonex',
  'Poly Tour Rev',
  '/images/seeds/reviews/string-spin.svg',
  '[]'::jsonb,
  '<p>這條線的咬球感明顯，適合用大幅度上旋、喜歡用彈跳高度壓迫對手的打法。</p><h2>張力建議</h2><p>一般成人競賽玩家可從 48-52 磅開始測試；若手肘敏感，建議降低張力或搭配較軟的橫線。</p><blockquote>重點不是越硬越會轉，而是你能不能完整加速揮拍。</blockquote>',
  'JoJo Tennis 編輯部',
  true,
  '2026-05-28T00:00:00Z',
  false
),
(
  '33333333-3333-4333-8333-333333333333',
  'Asics Solution Speed FF：紅土移動與急停評測',
  'asics-solution-speed-ff-clay-review',
  '球鞋',
  'Asics',
  'Solution Speed FF',
  '/images/seeds/reviews/shoe-court.svg',
  '[]'::jsonb,
  '<p>Solution Speed FF 的定位是速度型球鞋，前掌反應快，適合需要頻繁啟動與小碎步調整的球友。</p><h2>場地表現</h2><p>紅土版本的外底抓地足夠，但仍保留滑步空間。腳踝支撐不是最強，若你習慣大幅度橫移急停，可以考慮穩定型鞋款。</p>',
  'JoJo Tennis 編輯部',
  true,
  '2026-05-22T00:00:00Z',
  false
),
(
  '44444444-4444-4444-8444-444444444444',
  'Wilson Super Tour 9 Pack：通勤與比賽容量實測',
  'wilson-super-tour-9-pack-bag-review',
  '配件',
  'Wilson',
  'Super Tour 9 Pack',
  '/images/seeds/reviews/bag-essentials.svg',
  '[]'::jsonb,
  '<p>9 Pack 對多數球友是剛好的容量：兩到三支球拍、球鞋、換洗衣物、水壺與小物都能分層收納。</p><h2>適合族群</h2><ul><li>固定每週練球 2-4 次</li><li>需要帶鞋與毛巾通勤</li><li>偶爾參加賽事，需要備拍與補給</li></ul>',
  'JoJo Tennis 編輯部',
  true,
  '2026-05-18T00:00:00Z',
  false
)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  cover_image_url = excluded.cover_image_url,
  gallery = excluded.gallery,
  content_md = excluded.content_md,
  author_name = excluded.author_name,
  is_published = excluded.is_published,
  published_at = excluded.published_at,
  is_deleted = false,
  deleted_at = null,
  updated_at = now();
